# Primary development of this project occurs on Fruition's GitLab instance;
# push branches and tags to GitHub, where the Packagist integration is.

deploy-branches:
  only:
    - branches
  script:
    - cp $DEPLOY_KEY deploy && chmod 400 deploy
    - git remote add github git@github.com:fruition/mac-dev-shim.git || true
    - GIT_SSH_COMMAND="ssh -i deploy -o UserKnownHostsFile=$KNOWN_HOSTS"
      git push github HEAD:$CI_COMMIT_REF_NAME

deploy-tags:
  only:
    - tags
  script:
    - cp $DEPLOY_KEY deploy && chmod 400 deploy
    - git remote add github git@github.com:fruition/mac-dev-shim.git || true
    - GIT_SSH_COMMAND="ssh -i deploy -o UserKnownHostsFile=$KNOWN_HOSTS"
      git push --tags github
