# Primary development of this project occurs on Fruition's GitLab instance;
# push branches and tags to GitHub, where the Packagist integration is.

stages:
  - build
  - mirror

variables:
  GITHUB_REPO: "git@github.com:fruition/solr.git"

after_script:
  - docker logout || true

build:
  stage: build
  script:
    - docker login fruitionautomation -p $DOCKERHUB_TOKEN
    - ./build.sh

deploy-branches:
  stage: mirror
  only:
    - branches
  script:
    - cp $DEPLOY_KEY deploy && chmod 400 deploy
    - git remote remove github || true
    - git remote add github $GITHUB_REPO
    - GIT_SSH_COMMAND="ssh -i deploy -o UserKnownHostsFile=$KNOWN_HOSTS"
      git push github HEAD:$CI_COMMIT_REF_NAME

deploy-tags:
  stage: mirror
  only:
    - tags
  script:
    - cp $DEPLOY_KEY deploy && chmod 400 deploy
    - git remote remove github || true
    - git remote add github $GITHUB_REPO
    - GIT_SSH_COMMAND="ssh -i deploy -o UserKnownHostsFile=$KNOWN_HOSTS"
      git push --tags github
